name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [3.24.1]  # You can adjust the Flutter version as needed.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter ${{ matrix.flutter-version }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run flutter analyze
        run: flutter analyze

      - name: Run flutter tests
        run: flutter test
        
      - name: Build APK or IPA (optional)
        run: |
          flutter build web --release

      - name: Build Windows app
        run: flutter build windows --release

      - name: Upload Windows build
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/windows/runner/Release/